name: Deploy Product API to Uberspace

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via Rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".github" --exclude="node_modules"
          path: ./
          remote_path: /home/${{ vars.SSH_USERNAME }}/product-api
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies & restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.profile
            source ~/.zshrc
            cd ~/product-api
            npm install --omit=dev
            /home/${{ vars.SSH_USERNAME }}/bin/pm2 restart product-api || \
            /home/${{ vars.SSH_USERNAME }}/bin/pm2 start server.js --name product-api
